### ISSUE TITLE
Controll Hub Downgrade

### ISSUE THREAD

**Issue by torinriley** [CapitalRobotics/JanxArchive#3]
# Issue for pinning the project to 8.2.0
Just opening an issue here, thought it would be a good way to organize ideas. 

My initial thoughts where, after @blarghmatey changed the dependencies, 
```java 
dependencies {
    implementation 'org.firstinspires.ftc:Inspection:8.2.0'
    implementation 'org.firstinspires.ftc:Blocks:8.2.0'
    implementation 'org.firstinspires.ftc:RobotCore:8.2.0'
    implementation 'org.firstinspires.ftc:RobotServer:8.2.0'
    implementation 'org.firstinspires.ftc:OnBotJava:8.2.0'
    implementation 'org.firstinspires.ftc:Hardware:8.2.0'
    implementation 'org.firstinspires.ftc:FtcCommon:8.2.0'
    implementation 'org.firstinspires.ftc:Vision:8.2.0'
    implementation 'androidx.appcompat:appcompat:1.2.0'
}
```
To then change the version of the Android Gradle plugin from (7.2.0) to (4.1.3) thinking that when downgrading the andoird version you'd need to use an older version of the Android Gradle plugin.
```java
classpath 'com.android.tools.build:gradle:4.1.3'
```
In addition I tried to change the minSdkVersion, targetSdkVersion and compileSdkVersion in `build.gradel(FTC_Robot_controller)` and set it to 27, this means we'd be building for Android 8.1+ (API level 27), which is the closest match to Android 8.2.0 I could find.

```java

android {
    defaultConfig {
        minSdkVersion 27  // For Android 8.1+ (API level 27)
        targetSdkVersion 27  // Targeting Android 8.1 (API level 27)
        buildConfigField "String", "APP_BUILD_TIME", '"' + (new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ", Locale.ROOT).format(new Date())) + '"'
    }

    compileSdkVersion 27  // Compile against Android 8.1 (API level 27)

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    namespace = 'com.qualcomm.ftcrobotcontroller'
}
```
## --**ALSO** --
I ran into another major issue (maybe) when trying to use an older version of the android gradle plugin, it looks like I'm not able to use Java 12, and instead I need to use Java 8? 
```bash
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 66
```
So I'm pretty unsure as to how to deal with this, I'm not sure If changing the Android Gradle plugin is the best approach here, but I think if it is there might be some more major issues that might come up.
Asking for assistance here, wondering if someone could run this on their machine?

**Comment by slombardo31** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Get bot software back to working state for Fall Fest](https://trello.com/c/6JhBtCY6/48-get-bot-software-back-to-working-state-for-fall-fest)

**Comment by torinriley** [comment]
So this confirms what I was noticing before, to downgrade to the last supported version of Android on our controller, **we would need to downgrade our entire codebase to Java 8-11**, currently, we're using Java 17.


<img width="1307" alt="Screenshot 2024-09-22 at 6 48 33 PM" src="https://github.com/user-attachments/assets/a74a6881-cbde-4ec5-af43-7a5bc9dcb50b">

**Comment by cheesebroccoli** [comment]
Is that hard to do?

**Comment by torinriley** [comment]
I don't think so, but since we're using Java 17 we'd lose access to all the Java 17-specific features and libraries (idk if we're using any now) and it might make future development harder, I think you wouldn't be able to use sealed classes, pattern matching for `instanceof`, records, text blocks (multi-line strings) switch expressions, and the `NullPointerException` messages. probably missing some other ones. So idk if there's another way to do this, but I think this is kinda a big problem if we don't get the driver hub soon.

**Comment by cheesebroccoli** [comment]
Currently we arent using it now, and its not supposed to be a long term
solution I’d imagine, its for the fall fest mostly right?
